config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  authenticated :user do
    root to: 'categories#index', as: :authenticated_root
  end

  resources :categories, only: [:new, :create, :index] do
    resources :bills, only: [:new, :create, :index]
  end

  root to: 'splash#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :category_bills
  has_many :categories, through: :category_bills

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :category_bills
  has_many :bills, through: :category_bills
  has_one_attached :icon

  validates :name, presence: true
  validates :icon, presence: true

  def recent_bills
    bills.order('id ASC')
  end
end

app/models/category_bill.rb
class CategoryBill < ApplicationRecord
  belongs_to :category
  belongs_to :bill
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, foreign_key: 'author_id', class_name: 'Category'
  has_many :bills, foreign_key: 'author_id', class_name: 'Bill'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    categories_path
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |u|
      u.permit(:email, :password)
    end
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password_confirmation, :current_password)
    end
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :authenticate_user!
  # before_action :set_bill, only: %i[ show edit update destroy ]

  # GET /bills or /bills.json
  def index
    @category = current_category
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # POST /bills or /bills.json
  def create
    @category = current_category
    @bill = current_user.bills.new(bill_params)
    if @bill.save
      redirect_to category_bills_path(@category)
    else
      render :new
    end
  end

  def current_category
    @categories = current_user.categories.includes(:bills).find(params[:category_id])
  end

  private

  # Only allow a list of trusted parameters through.
  def bill_params
    params.require(:bill).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.where(author: current_user.id).order('id asc')
    @user = current_user
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.author = current_user
    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
      else
        flash[:alert] = 'Something went wrong, Try again!'
        render :new
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index; end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_bills_helper.rb
module CategoryBillsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/bills/_bill.html.erb
<div id="<%= dom_id bill %>" class="border border-black  m-3">
  <p class="m-3">
    <strong>Name:</strong>
    <%= bill.name %>
  </p>

  <p class="m-3">
    <strong>Amount:</strong>
    <%= bill.amount %>
  </p>

</div>

app/views/bills/_form.html.erb
 <%= form_with model: @bill, url: category_bills_url do |f| %>
    <div class="field my-3">
      <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "name", :required => true %>
    </div>

    <div class="field my-3">
      <%= f.number_field :amount, autofocus: true, class: "form-control", placeholder: "amount", :required => true%>
    </div>
    
    <div class="card checkbox m-3">
       <h3><%= f.label :categories, 'Select a Category', class: 'title m-3' %> </h3><br>
      <%= f.collection_check_boxes :category_ids, Category.where(author_id: current_user), :id, :name do |cat| %>
        <div class="checkbox-div m-3" >
          <%= cat.check_box %>
          <%= cat.label %><br>
        </div>
      <% end %>
    </div>

    <div class="text-center">
      <%= f.submit "Add Transaction", class:"btn green btn-lg m-4"  %>
    </div>
  <% end %>

app/views/bills/index.html.erb
<%= render partial: "shared/header", locals: { title: "ALL TRANSACTIONS" } %>

<div class="container  p-2 bg-white border-gray-1 rounded   mt-3 mb-3"">
  <% @category.recent_bills.each do |bill| %>
    <%= render bill %>
  <% end %>
</div>

  <div class="fixed-bottom text-center green">
   <%= link_to "New Transaction", new_category_bill_path, class:"btn green btn-lg m-4 p-4 border-white d-grid gap-2 "  %>
  </div>
</div>

app/views/bills/new.html.erb
<section class="container mt-3 text-center">
<h1>New Transaction</h1>

<%= render "form", bill: @bill %>

<br>

<div>
  <%= link_to "Back to Transactions", category_bills_path %>
</div>
</h1>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Icon:</strong>
    <%= category.icon %>
  </p>

</div>

app/views/categories/_form.html.erb
 <%= form_with model: @category do |form| %>
    <div class="my-3">
      <%= form.text_field :name, class: "form-control w-100", placeholder: "Name" %>
    </div>

    <div class="my-3">
      <%= form.file_field :icon, class: "form-control w-100", placeholder: "Icon" %>
    </div>

    <div class="text-center m-3">
      <%= form.submit "Save", class:"btn green btn-lg" %>
    </div>

  <% end %>

app/views/categories/index.html.erb
<section>
<%= render partial: "shared/navbar", locals: { title: "ALL TRANSACTIONS" } %>

<div class="container">
  <% @categories.each do |category| %>
    <%= link_to category_bills_path(category), class: "text-reset text-decoration-none" do %>
      <div class="category d-flex p-2 bg-white border-gray-1 rounded   mt-3 mb-3">
        <%= image_tag(category.icon, :alt => 'menu', :width => '80px', :height => '80px', class:'category-image align-self-center border border-gray-1 rounded') %>
        <div class="flex-grow-1 d-flex flex-column justify-content-end mx-1">
        <h3 class="color-text font-proxima-bold fs-6 no-link">
        <%= category.name %> </h3> 

            <span class="category-date color-text text-decoration-none font-proxima-light"><%= category.created_at %></span>
            <div class="ms-auto amount pt-3 pe-3">
             <span class="align-self-center color-text text-decoration-none font-proxima-light">$<%= category.bills.map { |b| b.amount }.sum %></span>
        </div>
         </div>

      </div>
    <% end %>
 <% end %>

  <div class="fixed-bottom text-center green ">
   <%= link_to 'Add New Category', new_category_path, class:"btn green btn-lg m-4 p-4 border-white d-grid gap-2"  %>
  </div>

</div>
</section>

app/views/categories/new.html.erb
<div class="container mt-5">
<h1 class="text-center">New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YourWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-secondary  bg-opacity-10">

  <main >
    <%= render 'shared/flash' %>
    <%= yield %>
  </main>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:success] %>
  <div class="alert alert-info mt4" role="alert">
    <%= flash[:success] %>
  </div>
<% end %>
<% if flash[:notice] %>
  <div class="alert alert-success mt4" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger mt4" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light blue text-light position-relative">
  <div class="container-fluid">
    <div class="d-flex align-items-center gap-4">
      <%= link_to '<-', categories_path, class: "text-light text-decoration-none fs-1 text"%>
        <h2 class="text-center m-0">TRANSACTIONS</h2>
      </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">                           
        </ul>
          <div class="d-flex justify-content-between gap-3 align-items-center">
              <%if user_signed_in?%>                
                  <strong>User:</strong>
                  <%= current_user.email %>                
                <%= button_to "Log Out", destroy_user_session_path, class: 'btn btn-outline-light', method: :delete  %>
              <%end%>
          </div>
        </div>
      </div>
    </nav>

app/views/shared/_navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-light blue text-light position-relative">
  <div class="container-fluid">
    <div class="d-flex align-items-center gap-4">
        <h2 class="text-center">CATEGORIES</h2>
      </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">                           
        </ul>
          <div class="d-flex justify-content-between gap-3 align-items-center">
              <%if user_signed_in?%>                
                  <strong>User:</strong>
                  <%= current_user.name %>                
                <%= button_to "Log Out", destroy_user_session_path, class: 'btn btn-outline-light', method: :delete  %>
              <%end%>
          </div>
        </div>
      </div>
    </nav>

app/views/splash/index.html.erb
<section class="d-flex flex-column align-items-center gap-3 vh-100 p-5" >

  
  <%= image_tag "Logo.png", width: '440px', height: '420px', class:'mb-3  ml-4'%> 
  <div class="text-center w-100">
    <%= link_to "LOG IN", new_user_session_path, class: 'btn blue w-75 mb-3'%>
    <%= link_to "SIGN UP", new_user_registration_path, class: 'btn blue w-75'%>
  </div>
</section>